CREATE TABLE [app].[Entry]
(
  [Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
  [DisableView] BIT NOT NULL DEFAULT(0),
  [TextEntry] NVARCHAR(MAX) NOT NULL,
  [DateCreated] DATETIME NOT NULL DEFAULT(GETDATE()),
  [DateModerated] DATETIME NULL
);
GO

ALTER TABLE app.Entry
ENABLE CHANGE_TRACKING;
